# OpenCV 


### Numpy 

##### Numpy is a python library used for working with arrays.
##### It stands for Numerical-Python.

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr)

[1 2 3 4 5 6 7]


## Slicing

In [2]:
arr[1:5]           # slicing

array([2, 3, 4, 5])

In [3]:
arr[0:5]

array([1, 2, 3, 4, 5])

In [6]:
arr[4:]

array([5, 6, 7])

In [7]:
arr[:4]

array([1, 2, 3, 4])

In [8]:
arr[-3:-1]

array([5, 6])

In [9]:
arr[:-2]

array([1, 2, 3, 4, 5])

In [10]:
arr.dtype  # data type of numpy array 

dtype('int64')

## Copy and View
- The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.
- The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.
- The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [14]:
arr1 = np.array([1,2,3,4,5])                # example for copy
x = arr1.copy()
arr1[0] = 17

print(arr1)
print(x)

[17  2  3  4  5]
[1 2 3 4 5]


In [15]:
arr1 = np.array([1,2,3,4,5])                # example for view 
x = arr1.view()
arr1[0] = 17

print(arr1)
print(x)

[17  2  3  4  5]
[17  2  3  4  5]


## shape of an array

In [16]:
## shape of an array 
arr.shape

(7,)

In [17]:
arr1.shape

(5,)

In [19]:
arr2 = np.array([12,45,78,12,84,94])
arr2.shape

(6,)

## Joining numpy array using concatenate()

In [29]:
arr1 = np.array([1,2,3,4,5])  

arr2 = np.array([12,45,78,12,84,94])

arr3 = np.concatenate((arr1,arr2))
print(arr3)



[ 1  2  3  4  5 12 45 78 12 84 94]


In [40]:
arr1 = np.array([[1, 2], [3, 4]])                 # 1-D array 

arr2 = np.array([[5, 6], [7, 8]])                 # 1-D array 

print("with axis")

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

print("without axis")

arr = np.concatenate((arr1, arr2))
print(arr)

with axis
[[1 2 5 6]
 [3 4 7 8]]
without axis
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Joining arrays using Stack Functions

In [42]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


### Joining arrays using Stack Functions

(Stacking along Rows)

In [43]:
#  (Stacking along Rows)
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


(Stacking along Columns)



In [44]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


(Stacking along height)

In [45]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


## Splitting Numpy Arrays
- Splitting is reverse operation of Joining.
- Joining merges multiple arrays into one and Splitting breaks one array into multiple.
- We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [47]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [48]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


## Numpy Searching Arrays

- You can search an array for a certain value, and return the indexes that get a match.
- To search an array, use the where() method.

In [53]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

y = np.where(arr == 2)

z = np.where(arr == 0)

print(x)
print(y)
print(z)

(array([3, 5, 6]),)
(array([1]),)
(array([], dtype=int64),)


In [54]:
# Example 2 

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)


(array([1, 3, 5, 7]),)


In [55]:
# Example 3 (Search Sorted)

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


## Numpy Sorting Arrays
- Sorting means putting elements in an ordered sequence
- Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.
- The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [56]:
arr = np.array([3, 2, 0, 1])
np.sort(arr)


array([0, 1, 2, 3])

In [57]:
# Example 2
arr = np.array(['banana', 'cherry', 'apple'])
np.sort(arr) 

array(['apple', 'banana', 'cherry'], dtype='<U6')

In [59]:
# Example 3 
arr = np.array([True, False, True])
np.sort(arr)

array([False,  True,  True])

In [61]:
# Sorting 2-D array 
arr = np.array([[3, 2, 4], [5, 0, 1]])
np.sort(arr)

array([[2, 3, 4],
       [0, 1, 5]])

## Numpy Filter Array
- Getting some elements out of an existing array and creating a new array out of them is called filtering.
- In NumPy, you filter an array using a boolean index list.
- If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.

In [64]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)
y = [False,True, True, False]
newarr1 = arr[y]
print(newarr1)

[41 43]
[42 43]


In [65]:
# Example 2
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(newarr)

[43 44]


## Random Numbers in Numpy


In [75]:
# Generate Random Number from 0 to 100
from numpy import random
x = random.randint(100)
print(x)

89


In [76]:
# Generate Random Float number between 0 and 1
x = random.rand()
print(x)

0.9581547778009913


In [77]:
# Generate Random Array
x1=random.randint(100, size=(5))
x2=random.randint(100, size=(3, 5))

print(x1)
print(x2)

[ 4 69 84 37 69]
[[56  3 72 46 18]
 [11 64 39 10 40]
 [59 17  3 89 30]]
